### ISSUE TITLE
XALT don't store json files for new users

### ISSUE THREAD

**Issue by zhum** [xalt/xalt#11]
XALT is configured with options ` --with-xaltFilePrefix=/mnt/scratch/xalt_stats --with-transmission=file`. While installation process script `create_xalt_directories.sh` was invoked and it created 997 subdirectories, named 000 ... 996. If we run any application in some subdir json files are created. But then we created new user and tried to run application and no new json files were appeared in any subdirectory. /mnt/scratch/xalt_stats has all rwx+t rights.

1. Why subdirectories 000 ... 996 were created, while in documentation is written, that they should be named $USER?
2. How to collect xalt data for new users?

**Comment by rtmclay** [comment]
XALT 2.7 and later now write directories, in your case /mnt/scratch/xalt_stats/000 to /mnt/scratch/xalt_stats/996 instead of /mnt/scratch/$USER.  

Thanks for pointing out an area where the documentation was out-of-date.  I have fixed it.

The reason for the change from writing to numbered directories instead of  $USER is to avoid a race condition.  If a user runs under XALT for the first time, two or more applications running at the same time might try to create the $USER directory at the same time and one or more might fail.  By creating the directories ahead of time, this race condition is prevented. 

My own tests show that the result files are being created and stored in the 000 to 996 directories.  Please check to see if the json result files to exist in those directories.

You can double check the results by running:

```
   XALT_SCALAR_SAMPLING=no XALT_TRACING=yes ./hello
```
Where ./hello is any simple executable.  You should see something like this:

```
...
xalt_run_submission(.zzz) {
  Built envT
  Extracted recordT from executable
  Built userT, userDT
  Filter envT
  Parsed ProcMaps
  Using XALT_TRANSMISSION_STYLE: file
  cmdlineA: ["./hello"]
  Built json string
  Wrote json run file: /home1/00515/mclay/.xalt.d/run.stampede2.2019_07_11_15_14_45_2648.mclay.zzz.5adca339-f901-4e71-b9e9-26e843e6b506.json
}
```
Are you seeing something different?

**Comment by zhum** [comment]
No, now works well. It seems to be some anomaly was happened while last test. May be old xalt varsion (0.5.0) was interfere.
If you could, please, add instructions how to upgrade old xalt to new. Can we migrate old data from database to new (now we've created a new one)?

**Comment by rtmclay** [comment]
I know of no easy way to transfer data from one mysql db to another.  There may be a way but you'll have to search the web for answers on how to do that.

Alternately, you could modify your old database to accept the new schema.  It has not changed much.  There are small number of columns added and a few that have been removed.

You can use mysql commands to modify the old db.  The changes in the columns in the xalt_link and xalt_run tables.  You can do a describe table for xalt_link in both the old and new databases then use the mysql "ALTER TABLE" commands to convert the old xalt_link to match the new schema for xalt_link.  Then you'll need to do the same for xalt_run.  Finally you'll need to add the xalt_pkg table to the old db.  Once this is done, you can add xalt 2.7 data into the old table.

Or you can just start storing data in the new table.

**Comment by zhum** [comment]
Ok, thank you. I store my new data in the new database and think about the way to import old data...
