### ISSUE TITLE
Module purge in sbatch scripts unloading Xalt

### ISSUE THREAD

**Issue by jstrelka** [xalt/xalt#14]
Is there a work around for xalt to track when users include "module purge" at the beginning of their scripts and never reload xalt? 
Thanks in advance.

**Comment by rtmclay** [comment]
XALT needs the following environment variables set:
```
XALT_EXECUTABLE_TRACKING=yes
XALT_SCALAR_SAMPLING=yes
LD_PRELOAD=/..../libxalt_init.so
```
You can set these variables in the startup scripts instead.  Say:   /etc/profile.d/xalt.sh and /etc/profile.d/xalt.csh.  

If you want to keep the xalt module, you can also make the xalt module sticky if you are using Lmod.  Users would have to do: "module --force purge" to remove it. 

Forcing users to use XALT can lead to problems.  If there is a problem with XALT then you have to tell a user to unset LD_PRELOAD rather than unloading the XALT module.  This rarely happens but it can.

**Comment by jstrelka** [comment]
Thank you I have it working outside of the modules environment by setting the environment variables in my local bash profile.
